services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "webappdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "111"
      PGDATA: "/home/user/postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - webappdb-data:/home/user/postgres
    ports:
      - "5432:5432"

volumes:
  webappdb-data: